<a href="https://colab.research.google.com/github/Aniket-Kumar-7/Deep-Learning/blob/main/AutoComplete.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sbn

In [4]:
df=pd.read_csv(r"/content/qoute_dataset.csv")

In [5]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [6]:
df['quote'][0]

'“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”'

In [7]:
quotes=df['quote']

In [8]:
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [9]:
quotes=quotes.str.lower()

In [10]:
import string

In [11]:
translator=str.maketrans('','',string.punctuation)
quotes.apply(lambda x: x.translate(translator))

0       “the world as we have created it is a process ...
1       “it is our choices harry that show what we tru...
2       “there are only two ways to live your life one...
3       “the person be it gentleman or lady who has no...
4       “imperfection is beauty madness is genius and ...
                              ...
3033         the past beats inside me like a second heart
3034    damn claire warn a guy before you do a facepla...
3035    can you be a girl for a few secondsim always a...
3036    thats what fiction is for its for getting at t...
3037    if we have no peace it is because we have forg...
Name: quote, Length: 3038, dtype: object

In [12]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [13]:
vocab_size=10000
tokenizer=Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(quotes)

In [14]:
word_index=tokenizer.word_index
print(len(word_index))
list(word_index.items())[:10]

8213

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [15]:
sequence=tokenizer.texts_to_sequences(quotes)

In [16]:
for i in range(3):
  print(quotes[i])

“the world as we have created it is a process of our thinking. it cannot be changed without changing our thinking.”
“it is our choices, harry, that show what we truly are, far more than our abilities.”
“there are only two ways to live your life. one is as though nothing is a miracle. the other is as though everything is a miracle.”

In [17]:
for i in range(3):
  print(sequence[i])

[732, 61, 30, 19, 17, 901, 10, 7, 5, 1188, 8, 71, 290, 10, 149, 12, 835, 103, 776, 71, 290, 136]
[977, 7, 71, 902, 388, 9, 431, 21, 19, 479, 14, 299, 51, 55, 71, 2545, 136]
[1384, 14, 53, 203, 700, 3, 80, 15, 37, 36, 7, 30, 300, 92, 7, 5, 1073, 1, 104, 7, 30, 300, 126, 7, 5, 1073, 136]

In [18]:
X=[]
y=[]

In [19]:
for seq in sequence:
  for i in range(1,len(seq)):
    input_seq=seq[:i]
    output_seq=seq[i];
    X.append(input_seq)
    y.append(output_seq)

In [20]:
len(X)

86549

In [21]:
len(y)

86549

In [22]:
max_len=max(len(x) for x in X)
max_len

748

In [23]:
import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [24]:
X_padded=pad_sequences(X,maxlen=max_len,padding='pre')

In [25]:
X_padded[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0, 732], dtype=int32)

In [26]:
y=np.array(y)
type(y)

numpy.ndarray

In [27]:
type(X_padded)

numpy.ndarray

In [28]:
X_padded.shape

(86549, 748)

In [29]:
y.shape

(86549,)

In [30]:
from tensorflow.keras.utils import to_categorical
y_one_hot=to_categorical(y,num_classes=vocab_size)

In [31]:
y_one_hot.shape

(86549, 10000)

In [32]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,SimpleRNN

In [33]:
embidding_dim=50
rnn_units=128

In [34]:
rnn_model=Sequential()

In [35]:
import warnings
warnings.filterwarnings('ignore')

In [36]:
rnn_model.add(
    Embedding(input_dim=vocab_size,output_dim=128,input_length=max_len)
)

In [37]:
rnn_model.add(SimpleRNN(units=rnn_units))
rnn_model.add(Dense(units=vocab_size,activation='softmax'))

In [38]:
rnn_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [39]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [40]:
lstm_model=Sequential()
lstm_model.add(
    Embedding(input_dim=vocab_size,output_dim=128,input_length=max_len)
)

In [41]:
lstm_model.add(SimpleRNN(units=rnn_units))
lstm_model.add(Dense(units=vocab_size,activation='softmax'))

In [42]:
lstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [43]:
epochs=10
batch_size=128

In [44]:
# history_rnn=rnn_model.fit(
#     X_padded,y_one_hot,epochs=epochs,batch_size=batch_size,validation_split=.1
# )

In [45]:
history_lstm=lstm_model.fit(
    X_padded,y_one_hot,epochs=epochs,batch_size=batch_size,validation_split=.1
)

Epoch 1/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 52s 78ms/step - accuracy: 0.0477 - loss: 6.6523 - val_accuracy: 0.0583 - val_loss: 6.4603
Epoch 2/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 44s 72ms/step - accuracy: 0.0890 - loss: 5.9824 - val_accuracy: 0.0999 - val_loss: 6.2027
Epoch 3/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 44s 72ms/step - accuracy: 0.1152 - loss: 5.5921 - val_accuracy: 0.1090 - val_loss: 6.1819
Epoch 4/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 44s 72ms/step - accuracy: 0.1342 - loss: 5.2859 - val_accuracy: 0.1121 - val_loss: 6.2137
Epoch 5/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 44s 72ms/step - accuracy: 0.1511 - loss: 5.0125 - val_accuracy: 0.1140 - val_loss: 6.2613
Epoch 6/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 44s 72ms/step - accuracy: 0.1676 - loss: 4.7569 - val_accuracy: 0.1124 - val_loss: 6.3516
Epoch 7/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 44s 71ms/step - accuracy: 0.1875 - loss: 4.5169 - val_accuracy: 0.1109 - val_loss: 6.4294
Epoch 8/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 44s 72ms/step - accuracy: 0.2109 - loss: 4.2871 - val_accuracy: 0.1060 - val_loss: 6.5190
Epoch 9/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 82s 72ms/step - accuracy: 0.2369 - loss: 4.0664 - val_accuracy: 0.1061 - val_loss: 6.6099
Epoch 10/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 44s 72ms/step - accuracy: 0.2643 - loss: 3.8595 - val_accuracy: 0.1043 - val_loss: 6.7041

In [46]:
lstm_model.save('lstm_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [47]:
index_to_word={}
for word,index in word_index.items():
  index_to_word[index]=word

In [48]:
def predictor(model,tokenizer,text,max_len):
  text=text.lower()
  seq=tokenizer.texts_to_sequences([text])[0]
  seq=pad_sequences([seq],maxlen=max_len,padding='pre')
  pred=model.predict(seq,verbose=0)
  pred_index=np.argmax(pred)
  return index_to_word[pred_index]

In [64]:
seed_text='I am the'
next_word=predictor(lstm_model,tokenizer,seed_text,max_len)
print(next_word)

ones

In [71]:
def generateText(model,tokenizer,seed_text,max_len,n_words):
  for _ in range(n_words):
    next_word=predictor(lstm_model,tokenizer,seed_text,max_len)
    if next_word == "":
      break
    seed_text+=" "+next_word
  return seed_text

In [81]:
seed="the world as we have created it is the process of our thinking.It can not "
full_Text=generateText(lstm_model,tokenizer,seed,max_len,20)
print(full_Text)

the world as we have created it is the process of our thinking.It can not  be a musician i am not a physicist i shall not be a musician i am not the same and

In [84]:
import pickle
with open("tokenizer.pkl","wb") as f:
  pickle.dump(tokenizer,f)

In [85]:
with open("max_len.pkl","wb") as f:
  pickle.dump(max_len,f)